#!/usr/bin/bash

capacity=$(cat /sys/class/power_supply/BAT1/capacity)
if [[ $capacity -le 20 ]]; then
   icon=""
elif [[ $capacity -le 40 ]]; then
    icon=""
elif [[ $capacity -le 60 ]]; then
    icon=""
elif [[ $capacity -le 80 ]]; then
    icon=""
else
    icon=""
fi

echo "$icon $capacity%"
